spring.application.name=sigamais

# Configuração de Conexão com o PostgreSQL no Neon
spring.datasource.url=jdbc:postgresql://ep-fragrant-forest-acpguyra-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_4G1JSADVsMjy&sslmode=require&channelBinding=require
spring.datasource.username=<Enio>
spring.datasource.password=<EnioJr@#18>
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
